version: '3'
volumes:
  mysqldata:

services:
    php:
        build:
            context: ./docker
            dockerfile: php.Dockerfile
        container_name: ${APP_NAME:?err}-php
        volumes:
            - './app:/var/www/html'
        depends_on:
            - mariadb

    nginx:
        image: nginx:latest
        container_name: ${APP_NAME:?err}-nginx
        ports:
            - '80:80'
            - '443:443'
        links:
            - 'php'
        volumes:
            - './app:/var/www/html'
            - './config/nginx:/etc/nginx/conf.d'

    mariadb:
        image: mariadb:latest
        container_name: ${APP_NAME:?err}-mariadb
        restart: 'on-failure'
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}
        ports:
        - "3306:3306"
        volumes:
            - mysqldata:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - 8080:80
        environment:
            PMA_HOST: mariadb
        depends_on:
            - mariadb
