#docker-compose up -d
#docker-compose ps
#docker-compose down
#docker-compose down --volumes
version: '3'
volumes:
  data:
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - data:/var/lib/mysql
#load file in directory sql alphabeticaly at creation
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
